// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOgvXQoMwGos3lKfqExDArDNYK2G4rZ7k',
    appId: '1:930866017476:web:769c20db90638ff154c591',
    messagingSenderId: '930866017476',
    projectId: 'not-enough-sake',
    authDomain: 'not-enough-sake.firebaseapp.com',
    storageBucket: 'not-enough-sake.firebasestorage.app',
    measurementId: 'G-MWF88N99QM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgox6qVDkvN6MrZ4MLecGRJ-QRVSLy62c',
    appId: '1:930866017476:android:723370a146e9afc354c591',
    messagingSenderId: '930866017476',
    projectId: 'not-enough-sake',
    storageBucket: 'not-enough-sake.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT5bpDFiyAhf3VAauuWLDDwUjWGwRo1KM',
    appId: '1:930866017476:ios:5a865b655f6f22c854c591',
    messagingSenderId: '930866017476',
    projectId: 'not-enough-sake',
    storageBucket: 'not-enough-sake.firebasestorage.app',
    androidClientId: '930866017476-nbs09ekfdlu4m65taq1h11sd8lhd28ka.apps.googleusercontent.com',
    iosClientId: '930866017476-ibnfenojtenn0dac19pu8hbi932rr1j0.apps.googleusercontent.com',
    iosBundleId: 'com.example.notEnoughSake',
  );
}
